### ISSUE TITLE
test2

### ISSUE THREAD

**Issue by fcakyon** [ultralytics/JSON2YOLO#84]
how is yolo segmentation format different than detection format?

**Comment by pderrenger** [comment]
@fcakyon hello!

YOLO segmentation format is an extension of its detection format, designed for instance segmentation tasks. While YOLO detection typically involves bounding boxes (x, y, width, height) and class IDs for objects, segmentation requires more detailed pixel-level information. 

In segmentation, YOLO uses polygons or masks to represent the exact shape of each instance, rather than just a bounding box. This means, for each object instance, you'll have a set of points defining the polygon around the object or a mask that highlights the object's exact pixels, alongside the class ID.

The change mainly involves how the object's presence and shape are defined, from boxes to more precise forms. For in-depth guidance on formats, visit our docs at https://docs.ultralytics.com 😊.

Hope this clears things up!
